import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="overflow-hidden h-full bg-primary">
        <div className="w-full h-16 bg-primary"></div>
        <div className="flex flex-row h-screen">
          <div className="w-60 bg-primary text-primary-text"><SideBar /></div>
          <div className="flex-1 bg-black text-primary-text w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
